package desired

import "strings"

type ConfigFile struct {
	Path    string
	Content string
}

func NeovimConfigFiles() []ConfigFile {
	return []ConfigFile{
		{Path: "init.lua", Content: neovimInit()},
		{Path: "lua/basic.lua", Content: neovimBasic()},
		{Path: "lua/keybindings.lua", Content: neovimKeybindings()},
		{Path: "lua/colorschema.lua", Content: neovimColorscheme()},
		{Path: "lua/plugins.lua", Content: neovimPlugins()},
		{Path: "lua/plugins-config/neoscroll.lua", Content: neovimNeoscrollConfig()},
		{Path: "lua/plugins-config/nvim-tree.lua", Content: neovimTreeConfig()},
		{Path: "lua/plugins-config/surround.lua", Content: neovimSurroundConfig()},
		{Path: "lua/plugins-config/toggleterm.lua", Content: neovimToggletermConfig()},
	}
}

func neovimInit() string {
	return strings.Join([]string{
		"-- Managed by Plasticine.",
		"require('basic')",
		"require('keybindings')",
		"require('plugins')",
		"require('colorschema')",
		"pcall(require, 'plugins-config.neoscroll')",
		"pcall(require, 'plugins-config.surround')",
		"",
	}, "\n")
}

func neovimBasic() string {
	return strings.Join([]string{
		"-- Managed by Plasticine.",
		"vim.g.encoding = 'UTF-8'",
		"vim.o.fileencoding = 'utf-8'",
		"vim.wo.number = true",
		"vim.wo.relativenumber = true",
		"vim.wo.cursorline = true",
		"vim.wo.signcolumn = 'yes'",
		"vim.o.tabstop = 2",
		"vim.bo.tabstop = 2",
		"vim.o.softtabstop = 2",
		"vim.o.shiftwidth = 2",
		"vim.bo.shiftwidth = 2",
		"vim.o.shiftround = true",
		"vim.o.expandtab = true",
		"vim.bo.expandtab = true",
		"vim.o.autoindent = true",
		"vim.bo.autoindent = true",
		"vim.o.smartindent = true",
		"vim.o.ignorecase = true",
		"vim.o.smartcase = true",
		"vim.o.hlsearch = false",
		"vim.o.incsearch = true",
		"vim.o.cmdheight = 1",
		"vim.o.autoread = true",
		"vim.bo.autoread = true",
		"vim.wo.wrap = false",
		"vim.o.whichwrap = '<,>,[,]'",
		"vim.o.hidden = true",
		"vim.o.mouse = 'a'",
		"vim.o.backup = false",
		"vim.o.writebackup = false",
		"vim.o.swapfile = false",
		"vim.o.updatetime = 300",
		"vim.o.timeoutlen = 500",
		"vim.o.splitbelow = true",
		"vim.o.splitright = true",
		"vim.g.completeopt = 'menu,menuone,noselect,noinsert'",
		"vim.o.termguicolors = true",
		"vim.opt.termguicolors = true",
		"vim.o.list = false",
		"vim.o.listchars = 'space:·,tab:··'",
		"vim.o.wildmenu = true",
		"vim.o.shortmess = vim.o.shortmess .. 'c'",
		"vim.o.pumheight = 10",
		"vim.o.showtabline = 2",
		"vim.o.showmode = false",
		"vim.opt.clipboard = 'unnamedplus'",
		"vim.g.loaded_netrw = 1",
		"vim.g.loaded_netrwPlugin = 1",
		"",
	}, "\n")
}

func neovimKeybindings() string {
	return strings.Join([]string{
		"-- Managed by Plasticine.",
		"local opt = { noremap = true, silent = true }",
		"local map = vim.api.nvim_set_keymap",
		"vim.g.mapleader = ' '",
		"vim.g.maplocalleader = ' '",
		"map('n', 'J', '5j', opt)",
		"map('n', 'K', '5k', opt)",
		"map('n', 'j', 'jzz', opt)",
		"map('n', 'k', 'kzz', opt)",
		"map('n', '<C-d>', '<C-d>zz', opt)",
		"map('n', '<C-u>', '<C-u>zz', opt)",
		"map('n', '<C-f>', '<C-f>zz', opt)",
		"map('n', '<C-b>', '<C-b>zz', opt)",
		"map('n', '<S-h>', '^', opt)",
		"map('n', '<S-l>', '$', opt)",
		"map('n', '<C-s>', ':w<CR>', opt)",
		"map('n', 'qq', ':q!<CR>', opt)",
		"map('n', '<C-n>', ':NvimTreeToggle<CR>', opt)",
		"map('n', '<C-t>', ':lua _FLOAT_TERM()<CR>', opt)",
		"map('n', '<leader>th', ':lua _HORIZONTAL_TERM()<CR>', opt)",
		"map('n', '<leader>tv', ':lua _VERTICAL_TERM()<CR>', opt)",
		"map('n', '<leader><leader>h', ':HopAnywhereBC<CR>', opt)",
		"map('n', '<leader><leader>l', ':HopAnywhereAC<CR>', opt)",
		"map('i', 'jk', '<Esc>', opt)",
		"map('i', '<C-h>', '<Esc>i', opt)",
		"map('i', '<C-j>', '<Esc>ja', opt)",
		"map('i', '<C-k>', '<Esc>ka', opt)",
		"map('i', '<C-l>', '<Esc>la', opt)",
		"map('v', '<S-h>', '^', opt)",
		"map('v', '<S-l>', '$', opt)",
		"map('o', '<S-h>', '^', opt)",
		"map('o', '<S-l>', '$', opt)",
		"",
	}, "\n")
}

func neovimColorscheme() string {
	return strings.Join([]string{
		"local colorscheme = 'tokyonight'",
		"local status_ok, _ = pcall(vim.cmd, 'colorscheme ' .. colorscheme)",
		"if not status_ok then",
		"  vim.notify('colorscheme: ' .. colorscheme .. ' not found!')",
		"end",
		"",
	}, "\n")
}

func neovimPlugins() string {
	return strings.Join([]string{
		"local ensure_packer = function()",
		"  local fn = vim.fn",
		"  local install_path = fn.stdpath('data') .. '/site/pack/packer/start/packer.nvim'",
		"  if fn.empty(fn.glob(install_path)) > 0 then",
		"    vim.notify('installing packer.nvim...')",
		"    fn.system({ 'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path })",
		"    vim.cmd [[packadd packer.nvim]]",
		"    return true",
		"  end",
		"  return false",
		"end",
		"",
		"local packer_bootstrap = ensure_packer()",
		"local status_ok, packer = pcall(require, 'packer')",
		"if not status_ok then",
		"  vim.notify('packer.nvim is not installed!')",
		"  return",
		"end",
		"",
		"packer.startup({",
		"  function(use)",
		"    use 'wbthomason/packer.nvim'",
		"    use 'folke/tokyonight.nvim'",
		"    use 'karb94/neoscroll.nvim'",
		"    use 'ur4ltz/surround.nvim'",
		"    use({ 'windwp/nvim-autopairs', config = function() require('nvim-autopairs').setup({}) end })",
		"    use({ 'phaazon/hop.nvim', branch = 'v2', config = function() require('hop').setup({ keys = 'etovxqpdygfblzhckisuran' }) end })",
		"    use({ 'nvim-tree/nvim-tree.lua', requires = { 'nvim-tree/nvim-web-devicons' }, config = function() require('plugins-config.nvim-tree') end })",
		"    use({ 'akinsho/toggleterm.nvim', tag = '*', config = function() require('plugins-config.toggleterm') end })",
		"    if packer_bootstrap then require('packer').sync() end",
		"  end,",
		"  config = { display = { open_fn = require('packer.util').float } }",
		"})",
		"pcall(vim.cmd, [[",
		"  augroup packer_user_config",
		"    autocmd!",
		"    autocmd BufWritePost plugins.lua source <afile> | PackerSync",
		"  augroup end",
		"]])",
		"",
	}, "\n")
}

func neovimNeoscrollConfig() string {
	return strings.Join([]string{
		"local status_ok, neoscroll = pcall(require, 'neoscroll')",
		"if not status_ok then return end",
		"neoscroll.setup({",
		"  mappings = { '<C-u>', '<C-d>', '<C-b>', '<C-f>', '<C-y>', '<C-e>', 'zt', 'zz', 'zb' },",
		"  hide_cursor = true,",
		"  stop_eof = true,",
		"  respect_scrolloff = false,",
		"  cursor_scrolls_alone = true,",
		"  easing_function = nil,",
		"  pre_hook = nil,",
		"  post_hook = nil,",
		"  performance_mode = false,",
		"})",
		"",
	}, "\n")
}

func neovimTreeConfig() string {
	return strings.Join([]string{
		"local status_ok, nvim_tree = pcall(require, 'nvim-tree')",
		"if not status_ok then return end",
		"local function my_on_attach(bufnr)",
		"  local api = require('nvim-tree.api')",
		"  local function opts(desc)",
		"    return { desc = 'nvim-tree: ' .. desc, buffer = bufnr, noremap = true, silent = true, nowait = true }",
		"  end",
		"  api.config.mappings.default_on_attach(bufnr)",
		"  vim.keymap.set('n', 'l', api.node.open.edit, opts('Open'))",
		"  vim.keymap.set('n', 'h', api.node.navigate.parent_close, opts('Close Directory'))",
		"  vim.keymap.set('n', 'o', api.node.open.edit, opts('Open'))",
		"  vim.keymap.set('n', '<CR>', api.node.open.edit, opts('Open'))",
		"  vim.keymap.set('n', 'v', api.node.open.vertical, opts('Open: Vertical Split'))",
		"  vim.keymap.set('n', 's', api.node.open.horizontal, opts('Open: Horizontal Split'))",
		"  vim.keymap.set('n', 'r', api.fs.rename, opts('Rename'))",
		"  vim.keymap.set('n', 'a', api.fs.create, opts('Create'))",
		"  vim.keymap.set('n', 'd', api.fs.remove, opts('Delete'))",
		"  vim.keymap.set('n', 'c', api.fs.copy.node, opts('Copy'))",
		"  vim.keymap.set('n', 'x', api.fs.cut, opts('Cut'))",
		"  vim.keymap.set('n', 'p', api.fs.paste, opts('Paste'))",
		"  vim.keymap.set('n', 'y', api.fs.copy.filename, opts('Copy Name'))",
		"  vim.keymap.set('n', 'Y', api.fs.copy.relative_path, opts('Copy Relative Path'))",
		"  vim.keymap.set('n', 'H', api.tree.toggle_hidden_filter, opts('Toggle Dotfiles'))",
		"  vim.keymap.set('n', 'R', api.tree.reload, opts('Refresh'))",
		"  vim.keymap.set('n', '?', api.tree.toggle_help, opts('Help'))",
		"end",
		"nvim_tree.setup({",
		"  on_attach = my_on_attach,",
		"  disable_netrw = true,",
		"  hijack_cursor = false,",
		"  hijack_netrw = true,",
		"  hijack_unnamed_buffer_when_opening = false,",
		"  open_on_tab = false,",
		"  sort_by = 'case_sensitive',",
		"  view = {",
		"    width = 30,",
		"    side = 'left',",
		"    preserve_window_proportions = false,",
		"    number = false,",
		"    relativenumber = false,",
		"    signcolumn = 'yes',",
		"  },",
		"  renderer = {",
		"    indent_markers = { enable = true, icons = { corner = '+ ', edge = '| ', none = '  ' } },",
		"    icons = {",
		"      webdev_colors = true,",
		"      git_placement = 'before',",
		"      padding = ' ',",
		"      symlink_arrow = ' ➛ ',",
		"      show = { file = true, folder = true, folder_arrow = true, git = true },",
		"      glyphs = {",
		"        default = '',",
		"        symlink = '',",
		"        folder = {",
		"          default = '',",
		"          empty = '',",
		"          empty_open = '',",
		"          open = '',",
		"          symlink = '',",
		"          symlink_open = '',",
		"          arrow_open = '',",
		"          arrow_closed = '',",
		"        },",
		"      },",
		"    },",
		"  },",
		"  hijack_directories = { enable = true, auto_open = true },",
		"  update_focused_file = { enable = true, update_root = true, ignore_list = {} },",
		"  diagnostics = {",
		"    enable = false,",
		"    show_on_dirs = false,",
		"    icons = { hint = '', info = '', warning = '', error = '' },",
		"  },",
		"  filters = { dotfiles = false, custom = {}, exclude = {} },",
		"  git = { enable = true, ignore = true, timeout = 500 },",
		"  actions = {",
		"    use_system_clipboard = true,",
		"    change_dir = { enable = true, global = false, restrict_above_cwd = false },",
		"    expand_all = { max_folder_discovery = 300 },",
		"    open_file = { quit_on_open = false, resize_window = true },",
		"  },",
		"  trash = { cmd = 'trash', require_confirm = true },",
		"  log = {",
		"    enable = false,",
		"    truncate = false,",
		"    types = { all = false, config = false, copy_paste = false, diagnostics = false, git = false, profile = false },",
		"  },",
		"})",
		"",
	}, "\n")
}

func neovimSurroundConfig() string {
	return strings.Join([]string{
		"local status_ok, surround = pcall(require, 'surround')",
		"if not status_ok then return end",
		"surround.setup({ mappings_style = 'surround' })",
		"",
	}, "\n")
}

func neovimToggletermConfig() string {
	return strings.Join([]string{
		"local status_ok, toggleterm = pcall(require, 'toggleterm')",
		"if not status_ok then return end",
		"toggleterm.setup({",
		"  size = function(term)",
		"    if term.direction == 'horizontal' then return 20 end",
		"    if term.direction == 'vertical' then return vim.o.columns * 0.4 end",
		"  end,",
		"  open_mapping = [[<c-t>]],",
		"  hide_numbers = true,",
		"  shade_filetypes = {},",
		"  shade_terminals = true,",
		"  shading_factor = 2,",
		"  start_in_insert = true,",
		"  insert_mappings = true,",
		"  persist_size = true,",
		"  direction = 'float',",
		"  close_on_exit = true,",
		"  shell = vim.o.shell,",
		"  float_opts = { border = 'curved', winblend = 0, highlights = { border = 'Normal', background = 'Normal' } },",
		"})",
		"function _G.set_terminal_keymaps()",
		"  local opts = { noremap = true }",
		"  vim.api.nvim_buf_set_keymap(0, 't', '<C-q>', [[<C-\\><C-n>]], opts)",
		"  vim.api.nvim_buf_set_keymap(0, 't', '<esc>', [[<C-\\><C-n>]], opts)",
		"  vim.api.nvim_buf_set_keymap(0, 't', '<C-l>', [[<C-c><C-u>clear<CR>]], opts)",
		"  vim.api.nvim_buf_set_keymap(0, 't', '<A-h>', [[<C-\\><C-n><C-W>h]], opts)",
		"  vim.api.nvim_buf_set_keymap(0, 't', '<A-j>', [[<C-\\><C-n><C-W>j]], opts)",
		"  vim.api.nvim_buf_set_keymap(0, 't', '<A-k>', [[<C-\\><C-n><C-W>k]], opts)",
		"  vim.api.nvim_buf_set_keymap(0, 't', '<A-l>', [[<C-\\><C-n><C-W>l]], opts)",
		"end",
		"vim.cmd('autocmd! TermOpen term://* lua set_terminal_keymaps()')",
		"local Terminal = require('toggleterm.terminal').Terminal",
		"local float_terminal = Terminal:new({ direction = 'float', on_open = function() vim.cmd('startinsert!') end, on_close = function() vim.cmd('startinsert!') end })",
		"local horizontal_terminal = Terminal:new({ direction = 'horizontal', on_open = function() vim.cmd('startinsert!') end, on_close = function() vim.cmd('startinsert!') end })",
		"local vertical_terminal = Terminal:new({ direction = 'vertical', on_open = function() vim.cmd('startinsert!') end, on_close = function() vim.cmd('startinsert!') end })",
		"function _FLOAT_TERM() float_terminal:toggle() end",
		"function _HORIZONTAL_TERM() horizontal_terminal:toggle() end",
		"function _VERTICAL_TERM() vertical_terminal:toggle() end",
		"",
	}, "\n")
}
